pipeline {
    agent any

    environment {
        DOCKER_IMAGE_DEV = "backend:dev"
        DOCKER_IMAGE_PROD = "backend:prod"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: "*/${env.BRANCH_NAME}"]],
                    userRemoteConfigs: [[
                        url: 'https://github.com/soaengry/moment.git',
                        credentialsId: 'github-token'
                    ]]
                ])
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'dev') {
                        sh "docker build -t ${DOCKER_IMAGE_DEV} -f backend/Dockerfile backend/"
                    } else if (env.BRANCH_NAME == 'main') {
                        sh "docker build -t ${DOCKER_IMAGE_PROD} -f backend/Dockerfile backend/"
                    } else {
                        error "Unsupported branch: ${env.BRANCH_NAME}"
                    }
                }
            }
        }

        stage('Deploy Container') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'dev') {
                        sh """
                        docker stop backend-dev || true
                        docker rm backend-dev || true
                        docker run -d -p 8081:8080 -e TZ=Asia/Seoul --name backend-dev -u root ${DOCKER_IMAGE_DEV}
                        """
                    } else if (env.BRANCH_NAME == 'main') {
                        sh """
                        docker stop backend-prod || true
                        docker rm backend-prod || true
                        docker run -d -p 8080:8080 -e TZ=Asia/Seoul --name backend-prod -u root ${DOCKER_IMAGE_PROD}
                        """
                    }
                }
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker images -qf dangling=true | xargs -r docker rmi'
            }
        }
    }
}
