spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret
  config:
    import: classpath:application-env.yml, classpath:application-common.yml, classpath:application-secret.yml

server:
  env: blue
