# Local
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
          naver:
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
          google:
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: moment

server:
  port: 8080
  name: local_server

app:
  email:
    verification-url: "http://localhost:8080/api/auth/verify-email"
    password-reset-url: "http://localhost:3000/reset-password"
  oauth2:
    redirect-uri: "http://localhost:3000/oauth2/callback"
  cors:
    allowed-origins: "http://localhost:3000"

---

# Blue
spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "${BASE_URL}/login/oauth2/code/kakao"
          naver:
            redirect-uri: "${BASE_URL}/login/oauth2/code/naver"
          google:
            redirect-uri: "${BASE_URL}/login/oauth2/code/google"

server:
  port: 8080
  name: blue_server

app:
  email:
    verification-url: "${BASE_URL}/api/auth/verify-email"
    password-reset-url: "${FRONT_URL}/reset-password"
  oauth2:
    redirect-uri: "${FRONT_URL}/oauth2/callback"
  cors:
    allowed-origins: "${FRONT_URL}"

---

# Green
spring:
  config:
    activate:
      on-profile: green

  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "${BASE_URL}/login/oauth2/code/kakao"
          naver:
            redirect-uri: "${BASE_URL}/login/oauth2/code/naver"
          google:
            redirect-uri: "${BASE_URL}/login/oauth2/code/google"

server:
  port: 8081
  name: green_server

app:
  email:
    verification-url: "${BASE_URL}/api/auth/verify-email"
    password-reset-url: "${FRONT_URL}/reset-password"
  oauth2:
    redirect-uri: "${FRONT_URL}/oauth2/callback"
  cors:
    allowed-origins: "${FRONT_URL}"

---

# dev
spring:
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "${BASE_URL}/login/oauth2/code/kakao"
          naver:
            redirect-uri: "${BASE_URL}/login/oauth2/code/naver"
          google:
            redirect-uri: "${BASE_URL}/login/oauth2/code/google"

server:
  port: 8080
  name: dev_server

app:
  email:
    verification-url: "${BASE_URL}/api/auth/verify-email"
    password-reset-url: "${FRONT_URL}/reset-password"
  oauth2:
    redirect-uri: "${FRONT_URL}/oauth2/callback"
  cors:
    allowed-origins: "${FRONT_URL}"
