spring:
  profiles:
    group:
      local: local, common
      blue: blue, common
      green: green, common
  config:
    import: classpath:application-env.yml, classpath:application-common.yml

server:
  env: blue
