spring:
  profiles:
    group:
      local: local, common
      blue: blue, common
      green: green, common
    active: local
  config:
    import: optional:file:.env[.properties], classpath:application-env.yml, classpath:application-common.yml

server:
  env: blue
