name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        working-directory: ./backend
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/moment_server -f backend/Dockerfile .

      - name: Push Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/moment_server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set target IP
        run: |
          STATUS=$(curl -o /dev/null -w "%{http_code}" "http://${{ secrets.MOMENT_SERVER_IP }}/env")
          echo $STATUS
          if [ $STATUS = 200 ]; then
            CURRENT_UPSTREAM=$(curl -s "http://${{ secrets.MOMENT_SERVER_IP }}/env")
          else
            CURRENT_UPSTREAM=green
          fi
          echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
          if [ $CURRENT_UPSTREAM = blue ]; then
            echo "CURRENT_PORT=8080" >> $GITHUB_ENV
            echo "STOPPED_PORT=8081" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
          elif [ $CURRENT_UPSTREAM = green ]; then
            echo "CURRENT_PORT=8081" >> $GITHUB_ENV
            echo "STOPPED_PORT=8080" >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
          else
            echo "error"
            exit 1
          fi

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@${{ secrets.MOMENT_SERVER_IP }} \
          "sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/moment_server:latest && \
           sudo docker compose -f docker-compose-${{env.TARGET_UPSTREAM}}.yml up -d"

      - name: Check deploy server URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://${{ secrets.MOMENT_SERVER_IP }}:${{env.STOPPED_PORT}}/env
          max-attempts: 3
          retry-delay: 10s

      # - name: Change nginx upstream
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@${{ secrets.MOMENT_SERVER_IP }} << EOF
      #     sudo docker exec moment-nginx sh -c 'echo "set \$service_url ${{ env.TARGET_UPSTREAM }};" > /etc/nginx/conf.d/service-env.inc'
      #     sudo docker exec moment-nginx nginx -s reload
      #     EOF
      - name: Change nginx upstream
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@${{ secrets.MOMENT_SERVER_IP }} \
          "sudo docker exec moment-nginx sh -c 'echo \"proxy_pass http://${{ env.TARGET_UPSTREAM }};\" > /etc/nginx/conf.d/upstream.inc' && \
           sudo docker exec moment-nginx nginx -s reload"
    
      - name: Stop current server
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@${{ secrets.MOMENT_SERVER_IP }} \
          "sudo docker stop ${{env.CURRENT_UPSTREAM}} && sudo docker rm ${{env.CURRENT_UPSTREAM}}"

      - name: Cleanup SSH key
        run: rm -f ssh_key.pem
